@isTest
public class testClassTest {

    @isTest
    static void testMethod1() {
        // Создаем экземпляр класса123123
        testClass obj = new testClass();

        // Здесь можно вызвать методы класса и проверять результаты
        // Например, если в классе есть методы, можно делать Sy123123stem.assert
        System.assertNotEquals(null, obj, 'Объект testClass должен быть создан');
    }
}